
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gsx2json
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gsx2json
  template:
    metadata:
      labels:
        app: gsx2json
    spec:
      imagePullSecrets:
        - name: maxroll-registry-v2
      containers:
        - name: gsx2json-container
          image: IMAGE
          env:
            - name: PORT
              value: "80"
            - name: GOOGLE_AUTH_KEY
              valueFrom:
                secretKeyRef:
                  name: gsx2json
                  key: api_key
          ports:
            - containerPort: 80
          readinessProbe:
            httpGet:
              path: /healthz
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /healthz
              port: 80
            initialDelaySeconds: 10
            periodSeconds: 15
