---
apiVersion: external-secrets.io/v1alpha1
kind: ExternalSecret
metadata:
  name: gsx2json
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-backend
  target:
    name: gsx2json
    creationPolicy: Owner
  data:
  - secretKey: "api_key"
    remoteRef:
      key: "gsx2json"
      property: "api_key"
