name: Build and Deploy
# run-name: Deploy triggered by @${{ github.actor }}

on:
  push:
    # branches:
    #   - main

env:
  IMAGE_NAME: gsx2json
  FULL_IMAGE: registry.maxroll.net:4000/gsx2json

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    environment:
      name: ${{ github.ref == 'refs/heads/main' && 'production' || 'staging' }}
    steps:
      - name: echo environment
        run: |
          echo "Environment: ${{ vars.ENV }}"
          echo "Image name: ${{ env.FULL_IMAGE }}"
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ env.FULL_IMAGE }}
          tags: |
            type=raw,value=latest,enable: ${{ github.ref == format('refs/heads/{0}', 'main') }}
            type=sha
      - name: Login to Docker Registry
        uses: docker/login-action@v2
        with:
          registry: registry.maxroll.net:4000
          username: ${{ secrets.MAXROLL_REGISTRY_USERNAME }}
          password: ${{ secrets.MAXROLL_REGISTRY_PASSWORD }}

      - uses: docker/setup-buildx-action@v2
      - uses: docker/build-push-action@v4
        with:
          context: .
          cache-from: type=gha
          cache-to: type=gha,mode=max
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

  deploy:
    name: 'Deploy to K8s'
    environment:
      name: ${{ github.ref == 'refs/heads/main' && 'production' || 'staging' }}
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@master
      - name: Set SHA
        id: set-sha
        run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
      - name: Echo image to deploy
        run: |
          echo "Deploying: ${{ env.FULL_IMAGE }}:sha-${{ steps.set-sha.outputs.sha_short }}"
      - name: Login to Docker Registry
        uses: docker/login-action@v2
        with:
          registry: registry.maxroll.net:4000
          username: ${{ secrets.MAXROLL_REGISTRY_USERNAME }}
          password: ${{ secrets.MAXROLL_REGISTRY_PASSWORD }}
      - uses: imranismail/setup-kustomize@v2
      - name: "Replace image name and auth key"
        run: |
          cd k8s
          kustomize edit set image IMAGE=${{ env.FULL_IMAGE }}:sha-${{ steps.set-sha.outputs.sha_short }}
      - name: Commit generated files
        run: |
          git config --global user.name 'Maxroll Bot'
          git config --global user.email 'contact@maxroll.gg'

          git add .
          git commit -m "[skip ci] Update deployment"
          git push
